name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  check:
    name: 'Check and build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: 'Check flake evaluates'
        run: nix flake check --no-build .
      - name: 'Build all packages'
        run: nix build -L .
      - name: 'Run checks'
        run: nix flake check -L .
